service:
  extensions: [jaeger_storage, jaeger_query, jaeger_mcp, healthcheckv2]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]
  telemetry:
    resource:
      service.name: jaeger
    logs:
      level: info

extensions:
  healthcheckv2:
    use_v2: true
    http:

  jaeger_query:
    storage:
      traces: memory_store
    ui: {}

  jaeger_mcp:
    http:
      endpoint: 0.0.0.0:16687

  jaeger_storage:
    backends:
      memory_store:
        memory:
          max_traces: 100000

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch: {}

exporters:
  jaeger_storage_exporter:
    trace_storage: memory_store
